/**
 * Launch articles for the Insights section.
 *
 * Written from the content plan's D1–D10 / I1–I7 outline. Deliberately no
 * dates in the copy — the owner asked for evergreen pieces, and the UI hides
 * publication dates for these so they don't age visibly. Anything genuinely
 * time-sensitive (market figures, LRS limits) is framed as "verify at the time
 * of your transaction" rather than stated as a current fact.
 */

export type SeedArticle = {
  title: string;
  slug: string;
  category: string;
  excerpt: string;
  readingMinutes: number;
  /** Plain paragraphs, or "## Heading" lines that become h2s. */
  body: string[];
};

export const SEED_ARTICLES: SeedArticle[] = [
  /* ---------------------------- DUBAI ---------------------------- */
  {
    title: "Profit is proven at exit, not in the brochure",
    slug: "profit-is-proven-at-exit",
    category: "Buyer guide",
    readingMinutes: 5,
    excerpt:
      "Entry price is a fact. Exit is an assumption. Most buyers spend all their diligence on the first and none on the second.",
    body: [
      "Every property purchase has two prices. The one you pay, which is a matter of record, and the one you eventually receive, which is a matter of hope. Buyers spend weeks negotiating the first and almost no time interrogating the second.",
      "This is the single most consistent error we see, in Dubai and in Gurgaon equally. The brochure shows a projected yield and an appreciation curve. Both are forecasts dressed as facts. Neither tells you the thing that actually determines your return: whether there will be a buyer for this specific unit, at a price you find acceptable, on the day you need to sell.",
      "## Why exit is harder than entry",
      "At entry you are one of many buyers competing for a scarce thing — the developer controls supply and sets the terms. At exit the position reverses entirely. You are one of many sellers, often holding a unit nearly identical to hundreds of others in the same building, competing against the developer who may still be releasing inventory in the same community at a discount.",
      "A tower with eight hundred similar units has eight hundred potential competing sellers. That is not a theoretical risk. It is arithmetic.",
      "## What we ask before recommending anything",
      "Who is the buyer for this unit in five years, and what are they optimising for? Is this unit type scarce in its area, or abundant? How much competing supply is scheduled to hand over within eighteen months of your likely exit window? What is the actual observed time-to-sale for comparable units, not the time-to-sale the agent quotes?",
      "If a property cannot answer those questions well, it can still be a fine home. It is a poor investment, and those are different purchases with different criteria.",
      "## The uncomfortable version",
      "A unit can be legally perfect, in a well-run building, from a reputable developer, and still be a bad investment — because everyone else owns one too. Legal safety and investment quality are separate axes. Dubai solved the first almost completely. It did nothing about the second, and confusing the two is how careful people lose money in a well-regulated market.",
    ],
  },
  {
    title: "Why Indians should not compare Dubai property to Indian property",
    slug: "dubai-is-not-indian-real-estate",
    category: "Buyer guide",
    readingMinutes: 6,
    excerpt:
      "Same instincts, wrong market. The habits that protect you in Gurgaon actively cost you money in Dubai.",
    body: [
      "Indian property buying is built on a set of instincts that are largely correct — for India. Land holds value. Location is permanent. You buy and you hold, often for a generation. Nobody sells the house.",
      "Those instincts are not transferable, and applying them to Dubai produces predictable, expensive mistakes.",
      "## Land versus building",
      "In India, a substantial share of what you buy is land, and land is finite. In Dubai, you are overwhelmingly buying a building on leasehold or freehold plots where supply is a policy decision, not a natural constraint. New towers can and do appear next to yours. The scarcity that protects an Indian asset often simply does not exist.",
      "## Holding period",
      "The Indian default is indefinite. The Dubai market rewards buyers who decide their holding period before they buy, because market cycles there are shorter and more pronounced. A property bought at the top of a cycle with no exit plan can take years to recover its entry price — which is survivable if you planned for it and painful if you did not.",
      "## Rental yield means something different",
      "Indian residential yields are famously low; nobody buys a Gurgaon flat for the rent. Dubai yields are genuinely attractive on paper, which draws Indian buyers who are not used to evaluating them — and who therefore do not deduct service charges, void periods, agency fees and maintenance before comparing. The gross figure on the brochure and the number that reaches your account are meaningfully different.",
      "## Transaction speed",
      "Selling a Gurgaon property can take months and involves a small circle of buyers. Dubai is faster and more liquid — but liquidity is concentrated in certain unit types and areas, and absent in others. Assuming uniform liquidity because the market as a whole is liquid is a specific and costly error.",
      "## What to carry across, and what to leave behind",
      "Carry across your scepticism, your insistence on documentation and your unwillingness to be rushed. Those serve you in any market. Leave behind the assumption that time alone fixes a bad entry, that land value provides a floor, and that a good building is the same thing as a good investment.",
    ],
  },
  {
    title: "What escrow actually protects you from — and what it doesn't",
    slug: "what-escrow-protects-you-from",
    category: "Legal & RERA",
    readingMinutes: 6,
    excerpt:
      "Escrow is real, statutory and genuinely protective. It also covers far less than most buyers assume.",
    body: [
      "Dubai introduced escrow for off-plan property in 2007, and it works. Buyer funds go into a supervised account tied to a specific project. Money is released to the developer against certified construction milestones. The developer cannot take your payment for tower A and spend it finishing tower B.",
      "This is a serious protection and it is why Dubai off-plan carries far less counterparty risk than most emerging markets. It is also routinely oversold, and understanding its edges matters more than celebrating its existence.",
      "## What escrow does cover",
      "Misappropriation of buyer funds between projects. Developers disappearing with deposits. Construction funded by nothing but the next round of buyers. These were real problems and escrow substantially solved them.",
      "## What escrow does not cover",
      "It does not guarantee your project completes. A developer can go insolvent with the escrow account intact and partially drawn; you become a creditor in a process, not a person with a finished apartment.",
      "It does not guarantee timing. Milestones certify that work happened, not that it happened on schedule. Delay is compatible with a perfectly functioning escrow account.",
      "It does not guarantee quality. Escrow releases against progress, not against workmanship. A certified milestone and a well-built floor are not the same claim.",
      "It says nothing about value. Escrow is indifferent to whether you overpaid, whether the area is oversupplied, or whether anyone will buy the unit from you later. It is a fund-protection mechanism, not an investment-quality mechanism.",
      "## The honest summary",
      "Escrow removes the risk of being defrauded. It does not remove the risk of being wrong. Almost all of the money that Indian buyers lose in Dubai is lost to the second category, and no amount of regulatory protection addresses it. That is what advisory is for.",
      "## A note on India",
      "RERA requires seventy per cent of buyer funds for a registered project to sit in a designated project account. The principle is similar; the enforcement is less mature and the coverage more variable. Where no equivalent mechanism exists at all, the substitute is negotiating a payment schedule that tracks construction progress — so your exposure grows only as the building does.",
    ],
  },
  {
    title: "Service charges: the number that quietly eats your yield",
    slug: "service-charges-eat-your-yield",
    category: "Market report",
    readingMinutes: 5,
    excerpt:
      "The most commonly ignored line in a Dubai investment case, and one of the largest.",
    body: [
      "Ask a buyer their expected yield and they will quote a gross figure. Ask what they are paying in service charges and there is usually a pause.",
      "Service charges are levied per square foot per year, set by the building's management and approved by the regulator. They cover maintenance, security, cleaning, insurance, chiller infrastructure and the reserve fund. They are unavoidable, they vary enormously between buildings, and they come off your rental income before you see any of it.",
      "## Why the variation matters so much",
      "Two towers in the same community, both handsome, both well-located, can carry materially different service charges. The difference is driven by amenity load, building efficiency, the quality of the management company and how honestly the reserve fund is provisioned.",
      "A building with extensive amenities — multiple pools, large lobbies, concierge, extensive landscaping — costs more to run. Those amenities may help you rent it. They may not help enough to cover what they cost you every year.",
      "## The reserve fund question",
      "The reserve fund pays for major replacement: chillers, lifts, façade work. A building charging suspiciously low service fees may simply be under-provisioning its reserve, which is not a saving. It is a deferred bill that arrives as a special assessment, usually at the worst moment.",
      "## What to actually do",
      "Get the current service charge figure per square foot, in writing, before you buy. Get the previous three years so you can see the trend. Ask whether a special assessment has been levied or is anticipated. Then recalculate your yield with that number deducted and decide whether the investment still holds.",
      "It frequently does. But a yield calculated before service charges is not a yield — it is a marketing number, and treating it as the former is how a sound-looking purchase quietly underperforms for a decade.",
    ],
  },
  {
    title: "Who buys this from you in five years?",
    slug: "who-buys-this-from-you",
    category: "Buyer guide",
    readingMinutes: 4,
    excerpt: "The first question we ask about any property, and the last one most buyers consider.",
    body: [
      "It is a simple question and it is remarkably hard to answer well. Say it out loud about any property you are considering: who, specifically, buys this from me in five years?",
      "Not the market. Not investors generally. A person, with a budget, a reason and alternatives.",
      "## Why the question works",
      "It forces every vague assumption into the open. If the answer is another investor, then you are betting the investment case still looks good to someone else later — which means you need to understand what would make it stop looking good. If the answer is an end-user family, then unit layout, school proximity and community maturity matter more than yield.",
      "If the honest answer is that you do not know, that is extremely useful information, and it is better to have it now.",
      "## The supply question underneath it",
      "Your buyer will have choices. How many units substantially identical to yours will be available at the same time? In a large tower, the answer is often hundreds — and every one of those sellers is your direct competitor, pricing against you.",
      "Scarcity is what protects an exit. Not quality, not location in the abstract, but the specific scarcity of the thing you own relative to demand for it.",
      "## Applying it",
      "Before committing, write down the buyer profile, what they will be comparing your unit against, and what would have to be true for them to choose yours. If that paragraph is hard to write, the investment case is weaker than the brochure suggests — regardless of how good the building is.",
    ],
  },
  {
    title: "Reading a Dubai payment plan: whose cash flow is it serving?",
    slug: "reading-a-dubai-payment-plan",
    category: "Buyer guide",
    readingMinutes: 5,
    excerpt:
      "A generous-looking payment plan is a pricing decision, not a favour. Here's how to read one.",
    body: [
      "Post-handover payment plans are the most effective sales tool in Dubai off-plan. Twenty per cent on booking, the rest spread over years after you get the keys — it sounds like the developer taking on risk for your benefit.",
      "Sometimes it is. Often it is a financing cost embedded in a higher headline price, and it is worth knowing which.",
      "## The trade you are actually making",
      "A developer offering extended post-handover terms is lending you money. That lending is priced, and the price is usually in the purchase figure. The comparison you want is not 'this plan versus no plan' but 'this plan and this price, versus a shorter plan at a lower price'.",
      "Ask directly what the price would be on a standard construction-linked plan. The gap is the cost of the finance. Then compare it against what borrowing that amount would actually cost you.",
      "## What a good plan looks like",
      "Payments tied to certified construction milestones rather than calendar dates. A meaningful share of the total falling due only at or after handover. Clear, written consequences if the developer misses their obligations, not just if you miss yours.",
      "## What a concerning plan looks like",
      "Heavy front-loading before substantial construction. Payments tied to dates rather than progress, which transfers delay risk entirely to you. Penalties that are precise and severe in one direction and vague in the other.",
      "## The asymmetry test",
      "Read the clauses covering your default and the developer's, side by side. If yours names an amount, a timeline and a mechanism, and theirs describes reasonable efforts, you are looking at an agreement written for one party. That imbalance is often negotiable — but only before you sign, and only if you noticed it.",
    ],
  },
  {
    title: "The Golden Visa: what it requires and what it doesn't grant",
    slug: "golden-visa-what-it-requires",
    category: "Legal & RERA",
    readingMinutes: 5,
    excerpt:
      "Widely misrepresented, frequently oversold, and a poor primary reason to buy property.",
    body: [
      "The UAE Golden Visa is a long-term renewable residency granted against qualifying investment, including property above a threshold value. It is genuine, it is valuable, and it is used to sell a great deal of unsuitable property.",
      "## What it is",
      "Long-term residency, renewable, not tied to an employer. It allows you to sponsor family members, hold residency without continuous physical presence requirements of the ordinary kind, and operate with the stability that a two-year employment visa does not offer.",
      "## What it is not",
      "It is not citizenship, and there is no pathway from it to citizenship. It is not a passport. It does not confer voting rights. It does not automatically make you a UAE tax resident — tax residency has its own separate tests, and assuming otherwise can create real problems with your Indian tax position.",
      "It also does not, by itself, make a property a good investment.",
      "## The mistake we see",
      "A buyer decides they want the visa, discovers a value threshold, and then buys the cheapest property that clears it. The visa is obtained. The property is mediocre — often deliberately priced at the threshold precisely because that is what it is for — and it underperforms for years while the owner tells themselves the visa justified it.",
      "The better sequence is to decide what property makes sense on its own merits, and then check whether it happens to qualify. If it does, the visa is a bonus. If your only route to qualification is a compromised asset, weigh that honestly.",
      "## On the numbers",
      "Thresholds, categories and the treatment of mortgaged or off-plan property have all changed more than once, and they can change again. Anyone quoting you a figure from memory — including us — should be checked against the current official position at the time of your transaction.",
    ],
  },
  {
    title: "Buying in Dubai without flying: how the remote purchase actually works",
    slug: "buying-in-dubai-without-flying",
    category: "Buyer guide",
    readingMinutes: 5,
    excerpt:
      "Remote purchase is standard in Dubai, not exceptional. Here is the sequence, and where it goes wrong.",
    body: [
      "A significant share of Dubai property is bought by people who have never stood in the unit. The infrastructure for this is mature and the process is genuinely workable — provided you replace the physical inspection with something equivalent rather than skipping it.",
      "## The sequence",
      "Brief and shortlist, done remotely. Verification of the developer, project registration and the specific unit. A structured remote viewing — not a marketing walkthrough, but unedited footage of the actual unit or, for off-plan, of the construction stage and the comparable completed product.",
      "Reservation and payment of the booking amount. Contract review before signature, not after. Execution, either digitally where permitted or through a power of attorney. Registration with the Land Department. Then the payment schedule runs, with progress verified at each milestone.",
      "## Where it goes wrong",
      "The first failure is accepting developer-supplied media as verification. Renders and show units tell you about intent, not delivery. Someone independent needs to look at what is actually being built.",
      "The second is signing before review. Remote buyers are often presented with contracts under time pressure attached to a launch price. A day spent reading is almost never the difference between getting and losing a good unit, whatever you are told.",
      "The third is losing visibility after payment starts. Off-plan is a multi-year relationship. Without someone checking progress against the schedule, the first you hear of a delay is when the handover date passes.",
      "## What to insist on",
      "Independent footage at each major milestone. Written confirmation of every payment against its milestone. A named person who will physically attend handover and snag the unit on your behalf. Remote purchase works well when someone is present on your side. It works badly when nobody is.",
    ],
  },
  {
    title: "Off-plan or ready: which Dubai strategy fits you",
    slug: "off-plan-or-ready",
    category: "Buyer guide",
    readingMinutes: 5,
    excerpt: "Not an argument about which is better. A decision tree about which is right for you.",
    body: [
      "The off-plan versus ready debate is usually conducted as though one answer exists. It does not. They are different instruments with different risk profiles, and the right choice falls out of your objective rather than the market's.",
      "## Off-plan suits you if",
      "You do not need income from the asset for some years. You can tolerate a delay of several quarters without it disrupting your plans. You are buying primarily for capital appreciation and you have a defined exit window with flexibility either side. You have the temperament to hold something you cannot see or use.",
      "## Ready suits you if",
      "You want rental income starting now. You want to inspect precisely what you are buying. You need certainty of timing — for residency, for a family move, for a specific plan. You would find a multi-year construction delay genuinely disruptive rather than merely annoying.",
      "## The risk each carries",
      "Off-plan carries delivery risk, delay risk and the risk that the market at handover is not the market at purchase. In exchange you typically get a lower entry price and staged payments.",
      "Ready carries none of the delivery risk but every bit of the valuation risk, immediately and in full. You are buying at today's price with no discount for patience, and the building's service charges and any deferred maintenance are yours from day one.",
      "## The question underneath",
      "Both roads end at the same place: can you exit when you need to, at a price that works? Off-plan defers that question. Ready presents it immediately. Neither answers it for you — which is why the analysis matters more than the category.",
    ],
  },
  {
    title: "The Dubai rental income reality check",
    slug: "dubai-rental-income-reality-check",
    category: "Market report",
    readingMinutes: 5,
    excerpt:
      "What the brochure yield leaves out — and what the number looks like once it's all in.",
    body: [
      "Advertised Dubai yields are attractive, and unlike some markets they are not fictional. They are just gross, and the distance between gross and net is where most of the disappointment lives.",
      "## What comes off the top",
      "Service charges, which we have written about separately and which are the largest single deduction. Property management, if you are not in the country to handle tenants yourself. Agency commission on each new letting. Void periods between tenants, which are a real cost even though nobody lists them. Maintenance and periodic refurbishment, because a unit that has been let for five years does not present like a new one.",
      "## The occupancy assumption",
      "Yield calculations almost always assume twelve months of rent. Model eleven instead, and model what happens if a tenant leaves in a soft quarter and the unit sits for two months. If the investment only works at full occupancy, it is more fragile than it appears.",
      "## Competing supply is the variable to watch",
      "Rent is set by what else a tenant can get. When a large volume of similar units hands over nearby, rents in that segment come under pressure regardless of how good your specific unit is. Handover schedules are public. Checking what is completing near your property in the next two years is an afternoon's work and it directly informs what you can expect to charge.",
      "## The honest framing",
      "Dubai rental income can be genuinely good. It is rarely as good as the headline, and the gap is predictable rather than mysterious. Anyone showing you a yield figure without deducting service charges is either not being careful or not being straight, and both are reasons to slow down.",
    ],
  },

  /* ---------------------------- INDIA ---------------------------- */
  {
    title: "Registry and mutation are not the same thing",
    slug: "registry-and-mutation",
    category: "Legal & RERA",
    readingMinutes: 5,
    excerpt:
      "The most common red flag in Haryana property, and the one buyers most often walk straight past.",
    body: [
      "A registered sale deed proves a transaction happened. Mutation — intkal — proves the revenue record was updated to reflect it. Buyers routinely assume the first automatically produces the second. It does not.",
      "## What each one is",
      "Registration is the recording of the transfer with the sub-registrar. It creates the legal instrument. Mutation is the subsequent updating of the revenue and land records to show the new owner as the person liable for property tax and recognised in local records.",
      "Registration is a one-off event. Mutation is an administrative follow-up that somebody has to actually go and do.",
      "## Why the gap causes problems",
      "If a property has been registered but never mutated, the revenue record still shows the previous owner. That creates difficulty when you come to sell, when you apply for a loan against the property, when utilities or tax authorities need to identify the owner, and in any dispute where the revenue record is treated as evidence of possession.",
      "The gap can persist through multiple transfers, and each one compounds it. A chain where two or three intermediate mutations were never completed is meaningfully harder to clean up than one.",
      "## How to check",
      "Ask for the current jamabandi or record of rights and read whose name appears. Compare it against the sale deed chain. If the names diverge, ask why, and get the answer in writing before you pay anything.",
      "This check costs nothing and takes very little time. It is skipped constantly, usually because the seller says it is a formality that will be handled after the transaction. Sometimes that is true. It is not something to accept on trust.",
    ],
  },
  {
    title: "The encumbrance certificate: what it is and how to pull one",
    slug: "encumbrance-certificate",
    category: "Legal & RERA",
    readingMinutes: 4,
    excerpt: "Free, quick, and almost nobody does it before paying a token.",
    body: [
      "An encumbrance certificate lists the registered transactions affecting a property over a stated period — sales, mortgages, liens and other charges. It answers a question a sale deed cannot: is anything else attached to this property?",
      "## What it catches",
      "An existing mortgage the seller has not mentioned. A prior agreement to sell. A lien from a lender. A charge arising from litigation. All of these can sit behind a deed that looks entirely clean on its face.",
      "## What it does not catch",
      "Unregistered transactions, oral arrangements, disputes not yet reflected in registered documents, and anything falling outside the period you requested. It is a necessary check, not a sufficient one — which is why it belongs alongside a title chain review and a litigation scan rather than instead of them.",
      "## How to get one",
      "Apply through the state's registration department portal or at the sub-registrar's office, with the property details and the period you want covered. Most states now offer this online. The fee is nominal and the turnaround is short.",
      "Request thirty years where you can. A shorter window is cheaper and faster and misses precisely the older complications that matter most.",
      "## When to do it",
      "Before the token, not after. Once money has changed hands the dynamic shifts entirely, and the pressure to proceed despite a finding becomes considerable. The whole value of this check is that it is cheap enough and fast enough to do while you can still walk away for nothing.",
    ],
  },
  {
    title: "Two possession dates: the one you were told and the one on RERA",
    slug: "two-possession-dates",
    category: "Legal & RERA",
    readingMinutes: 4,
    excerpt:
      "The date the builder gave the government is a matter of record. The one sales gave you is not.",
    body: [
      "When a project is registered under RERA, the promoter declares a completion date to the authority. That date is on the public record. Separately, a sales team tells buyers when they can expect possession. These two dates are often not the same, and the difference is instructive.",
      "## Which one is enforceable",
      "The registered date. Verbal assurances, brochure timelines and WhatsApp messages from a sales executive carry almost no weight when a project runs late. The declared date is what the delay framework attaches to.",
      "## How to check it",
      "Go to the relevant authority's portal — HRERA for Haryana, UP-RERA for Uttar Pradesh — and search the project by name or registration number. The registration details, declared completion date and, in many cases, quarterly progress filings are published.",
      "This takes a few minutes and requires nothing but the project name.",
      "## What a gap tells you",
      "If sales say eighteen months and the registered date is thirty-six, that is not necessarily fraud. It may be a conservative filing. But you should know which date you are being asked to plan around, and you should notice that the optimistic one is the one being used to sell to you.",
      "## What to do with it",
      "Plan around the registered date. Treat anything earlier as upside rather than expectation. And when you review the agreement, check that the delay clause references a date that actually exists in the registration rather than a vaguely defined target — a penalty attached to an undefined date is not a penalty.",
    ],
  },
  {
    title: "When a delay penalty clause is real — and when it's decoration",
    slug: "when-a-delay-penalty-is-real",
    category: "Legal & RERA",
    readingMinutes: 4,
    excerpt: "An amount, a trigger and a method. Miss any one and the clause does nothing.",
    body: [
      "Almost every builder agreement contains something described as a delay penalty. Very few contain one that could actually be enforced without litigation. The difference comes down to three elements.",
      "## One: a stated amount",
      "The clause must name a figure or a formula that produces one — a rate per square foot per month of delay, or a percentage of the amount paid. 'Compensation as mutually agreed' is not an amount. 'As per applicable law' pushes you into a process rather than giving you a right.",
      "## Two: a defined trigger",
      "Delay from when? The clause must reference a specific, identifiable date. Watch for grace periods stacked on top of the completion date, and for definitions that begin the count from an event the builder controls. A six-month grace period is common and not unreasonable; a grace period beginning at an undefined 'completion of structural works' is something else.",
      "## Three: a payment method",
      "How does the money actually reach you? Adjustment against the final instalment is the most common and the weakest — it only helps if you still owe enough at the end. Direct payment within a stated number of days is far stronger. If the clause does not say, assume adjustment and assume friction.",
      "## The symmetry check",
      "Read your own default clause immediately afterwards. If yours specifies interest at a punitive rate applied automatically, and theirs describes best efforts and mutual discussion, you have learned something about the agreement's authorship.",
      "This asymmetry is frequently negotiable, particularly on larger transactions and particularly before a launch closes. But only if you read the clause, and only before you sign it.",
    ],
  },
  {
    title: "Super built-up versus carpet area: what you actually bought",
    slug: "super-built-up-versus-carpet-area",
    category: "Buyer guide",
    readingMinutes: 5,
    excerpt: "The gap can be a third of your purchase price. It is also entirely knowable in advance.",
    body: [
      "Three area figures are used in Indian property and they describe different things. Understanding which one you are being priced on is the difference between comparing properties accurately and comparing them meaninglessly.",
      "## The three numbers",
      "Carpet area is the usable floor area within the walls of your unit — the space you can actually put furniture on. Built-up area adds the thickness of the walls and typically the balcony. Super built-up area adds your proportionate share of common spaces: lobbies, staircases, lifts, corridors, sometimes amenities.",
      "The gap between carpet and super built-up — the loading — commonly runs between twenty-five and forty per cent.",
      "## Why it matters beyond the headline",
      "Two properties quoted at the same rate per square foot can differ substantially in what you receive, purely because of different loading factors. Comparing rates without normalising to carpet area is comparing nothing at all.",
      "The Real Estate (Regulation and Development) Act defines carpet area specifically and requires it to be disclosed for registered projects. That was a meaningful reform. It did not stop pricing conversations from happening in super built-up terms, because the resulting rate sounds lower.",
      "## What to ask for",
      "The carpet area figure in writing, and the loading percentage. Then compute the price per square foot of carpet area and use only that number when comparing options. A property that looks expensive on carpet-area maths and cheap on super built-up maths is not cheap. It simply has a higher loading.",
      "## Resale implications",
      "Your eventual buyer will run the same calculation, or their advisor will. A high loading factor does not disappear because you accepted it — it follows the unit, and it prices into your exit exactly as it priced into your entry.",
    ],
  },
  {
    title: "“Only two units left” — how to check that in ten seconds",
    slug: "only-two-units-left",
    category: "Buyer guide",
    readingMinutes: 3,
    excerpt: "Scarcity is the oldest pressure tactic in property. It is also publicly verifiable.",
    body: [
      "Urgency is the most reliable tool in a sales conversation, and manufactured scarcity is its most common form. Two units left. Price rising Monday. Another buyer viewing this afternoon.",
      "Sometimes all of that is true. For registered projects, you can check rather than guess.",
      "## Where the real number lives",
      "Projects registered under RERA file inventory details with the authority — total units, and in many states the sold and unsold position, updated periodically. That filing is a regulatory submission, made under a different set of incentives from the ones operating in a sales office.",
      "Search the project on the relevant state portal and read the inventory disclosure.",
      "## What to do with a discrepancy",
      "If the filing shows substantial unsold inventory and you are being told two units remain, you have learned something valuable — not necessarily about the property, but about how information will be presented to you throughout this transaction.",
      "That is worth knowing before you are several instalments in.",
      "## The broader point",
      "Urgency is designed to prevent verification, because verification takes time and time dissolves urgency. Any process that requires you to decide before you can check is telling you something about itself. A genuinely good property survives a week of due diligence. It has to — your eventual buyer will apply the same scrutiny.",
    ],
  },
  {
    title: "How your parents bought a house, and why that method fails now",
    slug: "how-your-parents-bought-a-house",
    category: "Buyer guide",
    readingMinutes: 5,
    excerpt:
      "The generation before us bought on relationships and location. Both of those signals have weakened.",
    body: [
      "The previous generation's property method was coherent and it usually worked. Buy in a known locality. Deal with someone the family had used before, or someone known to someone. Hold for decades. Ignore the market.",
      "It worked because of conditions that have largely gone.",
      "## What made it work",
      "Supply was constrained and demand was growing, so time forgave almost any entry price. Localities were stable and their trajectories were legible over decades. The number of participants was small enough that reputation was a genuine enforcement mechanism — a broker who behaved badly lost the whole community.",
      "## What changed",
      "Supply expanded dramatically and unevenly, so 'it will appreciate eventually' stopped being reliably true for any specific property. New micro-markets appeared and matured in years rather than generations, making location judgement much harder. The market grew large enough that reputational enforcement stopped working — a broker can now behave badly and simply move to the next set of buyers.",
      "The information required to evaluate a purchase properly also grew. Registry, mutation, RERA, litigation, licensing: these existed before, but the volume and complexity of what needs checking has increased substantially.",
      "## What replaces it",
      "Verification replaces reputation. Not because people are less honest than they were, but because the mechanism that used to keep them honest no longer applies at this scale. You cannot rely on someone's standing in a community that is now too large to have one.",
      "That is an unsentimental conclusion and it is not a comfortable one. But a method that depends on conditions which no longer hold is not a safe method — it just feels like one, which is considerably more dangerous.",
    ],
  },
];
