import { createImageUrlBuilder } from "@sanity/image-url";
import type { Image } from "sanity";
import { dataset, projectId } from "@/lib/env";

const builder = createImageUrlBuilder({ projectId, dataset });

export type SanityImage = Image & {
  alt?: string;
  caption?: string;
  asset?: { _ref: string; _type: string };
};

/**
 * Build a Sanity CDN URL.
 *
 * We deliberately serve images straight from Sanity's CDN rather than through
 * Next's image optimizer: Vercel's Hobby plan meters image transformations,
 * Sanity's does not. `auto('format')` still gives us AVIF/WebP negotiation.
 */
export function urlFor(source: SanityImage | undefined | null) {
  if (!source?.asset) return null;
  return builder.image(source).auto("format").fit("max");
}

export function imageUrl(
  source: SanityImage | undefined | null,
  width: number,
  height?: number
): string | null {
  const b = urlFor(source);
  if (!b) return null;
  let img = b.width(width);
  if (height) img = img.height(height).fit("crop");
  return img.url();
}

/** Responsive srcset across the widths our layouts actually request. */
export function imageSrcSet(
  source: SanityImage | undefined | null,
  widths: number[] = [400, 640, 828, 1080, 1440, 1920],
  aspect?: number
): string | null {
  const b = urlFor(source);
  if (!b) return null;
  return widths
    .map((w) => {
      let img = b.width(w);
      if (aspect) img = img.height(Math.round(w / aspect)).fit("crop");
      return `${img.url()} ${w}w`;
    })
    .join(", ");
}

/**
 * A tiny blurred placeholder generated by the same CDN — 24px wide, heavily
 * compressed. Costs one extra request but kills layout-shift flashes.
 */
export function blurUrl(source: SanityImage | undefined | null): string | null {
  const b = urlFor(source);
  if (!b) return null;
  return b.width(24).quality(20).blur(20).url();
}

export function imageAlt(
  source: SanityImage | undefined | null,
  fallback: string
): string {
  return source?.alt?.trim() || fallback;
}
